### ISSUE TITLE
it is necessary to prompt after using LoRA to fine-tune SAMMed?

### ISSUE THREAD

**Issue by GuangzeShi** [YuancongLiang/SAMMed-LoRA#2]
This work is very interesting, but I want to know whether it is necessary to prompt after using LoRA to fine-tune SAMMed, so as to avoid the difference in results caused by different prompts.

**Comment by YuancongLiang** [comment]
Generally speaking, it is necessary. However, the tasks that our group focuses on do not require prompts. So in the code, there is no prompt training. If no prompts are introduced during the training process, but prompts are introduced during the inference stage, it may cause significant differences.
